# Values file for the Grafana helm chart located
# [here](https://github.com/grafana/helm-charts/tree/main/charts/grafana).

# The Grafana helm chart doesn't define an `app` label
podLabels:
  app: grafana

resources:
  requests:
    cpu: 10m
    memory: 10Mi
  limits:
    cpu: 100m
    memory: 128Mi

adminUser: admin
adminPassword: admin

service:
  type: NodePort
  nodePort: 30000

# Static datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability:3100
        jsonData:
          maxLines: 1000
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.observability:80
        # TODO
        #jsonData:
        #  exemplarTraceIdDestinations:
        #    - datasourceUid: jaeger
        #      name: traceID

# TODO: dashboards
