apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: loki-np
  labels:
    managed-by: setup-cluster.sh
spec:
  podSelector:
    matchLabels:
      app: loki
  policyTypes: [Ingress]

  # Allow Promtail to send logs to loki
  # Allow Prometheus to scrape metrics
  # Allow Grafana to read data from loki
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - {key: app, operator: In, values: [promtail, prometheus, grafana]}
      ports:
        - port: 3100
