apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: activemq-np
  labels:
    managed-by: setup-cluster.sh
spec:
  podSelector: 
    matchLabels:
      app: activemq
  policyTypes: [Ingress, Egress]

  # Allow access to the UI from any node in the cluster (for the NodePort
  # service)
  ingress:
    - ports:
        - port: 8161

    - from:
        - podSelector:
            matchLabels:
              activemq-client-amqp: enabled
      ports:
        - port: 5672

    - from:
        - podSelector:
            matchLabels:
              activemq-client-stomp: enabled
      ports:
        - port: 61613

    - from:
        - podSelector:
            matchLabels:
              activemq-client-openwire: enabled
      ports:
        - port: 61616

    - from:
        # Allow Prometheus to scrape metrics from any namespace
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: prometheus
      ports:
        - port: 15020
