apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-pvc
  labels:
    managed-by: setup-cluster.sh
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
