# Values file for the Loki helm chart located
# [here](https://github.com/grafana/helm-charts/tree/main/charts/loki).

resources:
  requests:
    cpu: 10m
    memory: 10Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  accessModes: [ReadWriteOnce]
  size: 2G
  storageClassName: standard

# TODO
#tracing:
#  jaegerAgentHost: ?
