# Values file for the Promtail helm chart located
# [here](https://github.com/grafana/helm-charts/tree/main/charts/promtail).

resources:
  requests:
    cpu: 10m
    memory: 10Mi
  limits:
    cpu: 200m
    memory: 128Mi

config:
  lokiAddress: http://loki:3100/loki/api/v1/push
