apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mariadb.fullname" . }}-deployment
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate  # Two MariaDB pods can't share the same volume on /var/lib/mysql
  selector:
    matchLabels:
      app: {{ include "mariadb.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "mariadb.fullname" . }}
        release: {{ .Release.Name }}
        {{- include "mariadb.labels" . | nindent 8 }}
      {{- if .Values.enableMetrics }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
      {{- end }}
    spec:
      serviceAccountName: {{ include "mariadb.fullname" . }}-sa
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: {{ include "mariadb.fullname" . }}-pvc
        - name: init-scripts
          configMap:
            name: {{ include "mariadb.fullname" . }}-init-cm
        {{- range $index, $secret_name := .Values.dbconfigSecrets }}
        - name: db{{ $index }}
          secret:
            secretName: {{ $secret_name }}
        {{- end }}
      containers:
        - name: mariadb
          image: "mariadb:{{ .Chart.AppVersion }}"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            {{- range $index, $secret_name := .Values.dbconfigSecrets }}
            - name: db{{ $index }}
              mountPath: /secrets/db{{ $index }}
              readOnly: true
            {{- end }}
          livenessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -u root \"-p$MYSQL_ROOT_PASSWORD\""]
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -u root \"-p$MYSQL_ROOT_PASSWORD\""]
            initialDelaySeconds: 20
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rootPasswordSecret }}
                  key: rootPassword
            - name: OLD_MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rootPasswordSecret }}
                  key: oldRootPassword

{{- if .Values.enableMetrics }}
        - name: exporter
          image: prom/mysqld-exporter
          ports:
            - name: metrics
              containerPort: 9104
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rootPasswordSecret }}
                  key: rootPassword
            - name: DATA_SOURCE_NAME
              value: "root:$(MYSQL_ROOT_PASSWORD)@(localhost:3306)/"
{{- end }}
