apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mariadb.fullname" . }}-pvc
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.storageSizeGb }}G"
