apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}-root-password-secret
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootPassword: {{ .Values.rootPassword | quote }}
{{- $index := 0 }}
{{- range $index, $cfg := .Values.dbconfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" $ }}-{{ $index }}
  labels:
    {{- include "mariadb.labels" $ | nindent 4 }}
type: Opaque
stringData:
  dbname: {{ $cfg.dbname | quote }}
  username: {{ $cfg.username | quote }}
  password: {{ $cfg.password | quote }}
{{- $index := (add $index 1 ) }}
{{- end }}
