version: "2.4"

services:
  mariadb:
    image: mariadb:10.2
    init: true
    restart: always
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: zie3Ethi
      MYSQL_USER: alfresco
      MYSQL_PASSWORD: hei4aeY9
      MYSQL_DATABASE: alfresco
    ports:
      - 3306:3306

  activemq:
    image: alfresco/alfresco-activemq:5.15.8
    init: true
    ports:
      - 8161:8161  # Web console
      - 5672:5672  # AMQP
      - 61616:61616  # OpenWire
      - 61613:61613  # STOMP

  acs-repository:
    image: ${account_id}.dkr.ecr.${region}.amazonaws.com/acs-repository:${acs_repository_tag}
    init: true
    build:
      context: ./acs-repository
    volumes:
      - alfdata-volume:/usr/local/tomcat/alf_data
      - ./easyrsa/pki:/etc/minipki:ro
    environment:
      JAVA_OPTS: >
        -Ddir.root=/usr/local/tomcat/alf_data
        -Ddb.driver=org.mariadb.jdbc.Driver
        -Dindex.subsystem.name=noindex
        -Dshare.host=ark-haproxy
        -Dshare.port=9443
        -Dshare.protocol=https
        -Dalfresco.host=ark-haproxy
        -Dalfresco.port=9443
        -Dalfresco.protocol=https
        -Daos.baseUrlOverwrite=https://ark-haproxy:9443/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Ddeployment.method=DOCKER_COMPOSE
        -Dhttp.proxyHost=ark-haproxy
        -Dhttp.proxyPort=9080
        -Dhttps.proxyHost=ark-haproxy
        -Dhttps.proxyPort=9443
        -Djodconverter.enabled=false
        -Djodconverter.officeHome=null
        -Xms1500m
        -Xmx1500m
        -Dlocal.transform.service.enabled=false
        -Dtransform.service.enabled=false
        -Dlegacy.transform.service.enabled=false
        -DsyncService.mode=OFF
        -Dsync.mode=OFF
        -Dsync.pullJob.enabled=false
        -Dsync.pushJob.enabled=false
        -Dsystem.usages.enabled=false
        -Dsystem.usages.clearBatchSize=0
        -Dactivities.feed.notifier.enabled=false
        -Dactivities.feed.cleaner.enabled=false
        -Dactivities.post.cleaner.enabled=false
        -Dactivities.feed.generator.enabled=false
        -Dactivities.post.lookup.enabled=false
        -Dreplication.enabled=false
        -Dtransferservice.receiver.enabled=false
        -Dsystem.thumbnail.generate=false
      DC_DB_USERNAME: alfresco
      DC_DB_PASSWORD: hei4aeY9
      DC_DB_URL: jdbc:mariadb://mariadb:3306/alfresco?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    depends_on:
      - mariadb

  nginx-acs-repository:
    image: ${account_id}.dkr.ecr.${region}.amazonaws.com/nginx-acs-repository:${nginx_acs_repository_tag}
    init: true
    build:
      context: ./nginx-acs-repository
    environment:
      ACM_NGINX_ACS_REPO_HOST: acs-repository
      ACM_NGINX_ACS_REPO_PORT: 8080
    depends_on:
      - acs-repository
    ports:
      - 5443:5443

  acs-share:
    image: ${account_id}.dkr.ecr.${region}.amazonaws.com/acs-share:${acs_share_tag}
    init: true
    build:
      context: ./acs-share
    volumes:
      - ./easyrsa/pki:/etc/minipki:ro
    environment:
      REPO_HOST: ark-haproxy
      REPO_PORT: 9443
      REPO_PROTO: https
      CSRF_FILTER_REFERER: https://ark-haproxy:9443/.*
      CSRF_FILTER_ORIGIN: https://ark-haproxy:9443
      JAVA_OPTS: >
        -Xms500m
        -Xmx500m
        -Dshare.host=ark-haproxy
        -Dshare.port=9443
        -Dshare.protocol=https
        -Dalfresco.context=alfresco
        -Dhttp.proxyHost=ark-haproxy
        -Dhttp.proxyPort=9080
        -Dhttps.proxyHost=ark-haproxy
        -Dhttps.proxyPort=9443
      DC_DB_USERNAME: alfresco
      DC_DB_PASSWORD: hei4aeY9
      DC_DB_URL: jdbc:mariadb://mariadb:3306/alfresco?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    depends_on:
      - mariadb

  nginx-acs-share:
    image: ${account_id}.dkr.ecr.${region}.amazonaws.com/nginx-acs-share:${nginx_acs_share_tag}
    init: true
    build:
      context: ./nginx-acs-share
    environment:
      ACM_NGINX_ACS_SHARE_HOST: acs-share
      ACM_NGINX_ACS_SHARE_PORT: 8080
    depends_on:
      - acs-share
    ports:
      - 6443:6443

  ark-haproxy:
    image: ${account_id}.dkr.ecr.${region}.amazonaws.com/ark-haproxy:${ark_haproxy_tag}
    init: true
    build:
      context: ./ark-haproxy
    volumes:
      - ./easyrsa/pki:/etc/minipki:ro
    environment:
      ACM_HAPROXY_DOMAIN_NAME: ${domain_name}
      ACM_HAPROXY_ACS_REPO_HOST: nginx-acs-repository
      ACM_HAPROXY_ACS_REPO_HTTPS_PORT: 5443
      ACM_HAPROXY_ACS_SHARE_HOST: nginx-acs-share
      ACM_HAPROXY_ACS_SHARE_HTTPS_PORT: 6443
    depends_on:
      - nginx-acs-repository
      - nginx-acs-share
    ports:
      - 9080:9080
      - 9443:9443

volumes:
  mariadb-volume:
  alfdata-volume:
