version: "3"

services:
  mariadb:
    image: mariadb:10.2
    restart: always
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: zie3Ethi
      MYSQL_USER: alfresco
      MYSQL_PASSWORD: hei4aeY9
      MYSQL_DATABASE: alfresco
    ports:
      - 3306:3306

  activemq:
    image: alfresco/alfresco-activemq:5.15.8
    ports:
      - 8161:8161  # Web console
      - 5672:5672  # AMQP
      - 61616:61616  # OpenWire
      - 61613:61613  # STOMP

  alfresco:
    build:
      context: ./repository
    volumes:
      - alfdata-volume:/usr/local/tomcat/alf_data
    environment:
      JAVA_OPTS: >
        -Ddb.driver=org.mariadb.jdbc.Driver
        -Ddb.username=alfresco
        -Ddb.password=hei4aeY9
        -Ddb.url="jdbc:mariadb://mariadb:3306/alfresco?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8"
        -Dindex.subsystem.name=noindex
        -Dshare.host=${DNS_NAME}
        -Dshare.port=8080
        -Dalfresco.host=${DNS_NAME}
        -Dalfresco.port=8080
        -Daos.baseUrlOverwrite=http://${DNS_NAME}:8080/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Ddeployment.method=DOCKER_COMPOSE
        -Dcsrf.filter.enabled=false
        -Djodconverter.enabled=false
        -Djodconverter.officeHome=null
        -Xms1500m -Xmx1500m
        -Dlocal.transform.service.enabled=false
        -Dtransform.service.enabled=false
        -Dlegacy.transform.service.enabled=false
        -DsyncService.mode=OFF
        -Dsync.mode=OFF
        -Dsync.pullJob.enabled=false
        -Dsync.pushJob.enabled=false
        -Dsystem.usages.enabled=false
        -Dsystem.usages.clearBatchSize=0
        -Dactivities.feed.notifier.enabled=false
        -Dactivities.feed.cleaner.enabled=false
        -Dactivities.post.cleaner.enabled=false
        -Dactivities.feed.generator.enabled=false
        -Dactivities.post.lookup.enabled=false
        -Dreplication.enabled=false
        -Dtransferservice.receiver.enabled=false
        -Dsystem.thumbnail.generate=false

  share:
    image: alfresco/alfresco-governance-share-community:V3.3.1.x-latest
    environment:
      REPO_HOST: alfresco
      REPO_PORT: 8080
      JAVA_OPTS: >
        -Xms500m
        -Xmx500m
        -Dalfresco.host=${DNS_NAME}
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http

  nginx:
    image: alfresco/acs-community-ngnix:1.0.0
    depends_on:
      - alfresco
    ports:
      - 8080:8080

volumes:
  mariadb-volume:
  alfdata-volume:
