version: "2.4"

services:
  mariadb:
    image: mariadb:10.2
    init: true
    restart: always
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: zie3Ethi
      MYSQL_USER: alfresco
      MYSQL_PASSWORD: hei4aeY9
      MYSQL_DATABASE: alfresco
    ports:
      - 3306:3306

  activemq:
    image: alfresco/alfresco-activemq:5.15.8
    init: true
    ports:
      - 8161:8161  # Web console
      - 5672:5672  # AMQP
      - 61616:61616  # OpenWire
      - 61613:61613  # STOMP

  acs-repository:
    image: ${account_id}.dkr.ecr.${region}.amazonaws.com/acs-repository:${acs_repository_tag}
    init: true
    build:
      context: ./acs-repository
    volumes:
      - alfdata-volume:/usr/local/tomcat/alf_data
    environment:
      JAVA_OPTS: >
        -Ddb.driver=org.mariadb.jdbc.Driver
        -Dindex.subsystem.name=noindex
        -Dshare.host=${domain_name}
        -Dshare.port=9443
        -Dshare.protocol=https
        -Dalfresco.host=${domain_name}
        -Dalfresco.port=8443
        -Dalfresco.protocol=https
        -Daos.baseUrlOverwrite=https://${domain_name}:8443/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Ddeployment.method=DOCKER_COMPOSE
        -Dcsrf.filter.enabled=false
        -Djodconverter.enabled=false
        -Djodconverter.officeHome=null
        -Xms1500m
        -Xmx1500m
        -Dlocal.transform.service.enabled=false
        -Dtransform.service.enabled=false
        -Dlegacy.transform.service.enabled=false
        -DsyncService.mode=OFF
        -Dsync.mode=OFF
        -Dsync.pullJob.enabled=false
        -Dsync.pushJob.enabled=false
        -Dsystem.usages.enabled=false
        -Dsystem.usages.clearBatchSize=0
        -Dactivities.feed.notifier.enabled=false
        -Dactivities.feed.cleaner.enabled=false
        -Dactivities.post.cleaner.enabled=false
        -Dactivities.feed.generator.enabled=false
        -Dactivities.post.lookup.enabled=false
        -Dreplication.enabled=false
        -Dtransferservice.receiver.enabled=false
        -Dsystem.thumbnail.generate=false
      DC_DB_USERNAME: alfresco
      DC_DB_PASSWORD: hei4aeY9
      DC_DB_URL: jdbc:mariadb://mariadb:3306/alfresco?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8

  nginx-acs-repository:
    image: ${account_id}.dkr.ecr.${region}.amazonaws.com/nginx-acs-repository:${nginx_acs_repository_tag}
    init: true
    build:
      context: ./nginx-acs-repository
    environment:
      ACM_NGINX_DOMAIN_NAME: localhost
      ACM_NGINX_ACS_REPO_HOST: acs-repository
      ACM_NGINX_ACS_REPO_PORT: 8080
    ports:
      - 8180:8180
      - 8443:8443

  acs-share:
    # XXX image: alfresco/alfresco-governance-share-community:V3.3.1.x-latest
    image: alfresco/alfresco-share:6.2.2
    init: true
    environment:
      REPO_HOST: nginx-acs-repository
      REPO_PORT: 8443
      JAVA_OPTS: >
        -Xms500m
        -Xmx500m
        -Dalfresco.host=${domain_name}
        -Dalfresco.port=8443
        -Dalfresco.protocol=https
        -Dalfresco.context=alfresco

  nginx-acs-share:
    image: ${account_id}.dkr.ecr.${region}.amazonaws.com/nginx-acs-share:${nginx_acs_share_tag}
    init: true
    build:
      context: ./nginx-acs-share
    environment:
      ACM_NGINX_DOMAIN_NAME: localhost
      ACM_NGINX_ACS_SHARE_HOST: acs-share
      ACM_NGINX_ACS_SHARE_PORT: 8080
    ports:
      - 9180:9180
      - 9443:9443

volumes:
  mariadb-volume:
  alfdata-volume:
