version: "2.4"  # docker-compose version 3 doesn't support "init: true"

services:
  test-backend:
    # NB: The `test-backend` image is build in "../nginx-tls"
    depends_on: [ envoy-tls ]
    image: ${account_id}.dkr.ecr.${region}.amazonaws.com/test-backend:${test_backend_tag}
    init: true
    environment:
      - HOSTNAME=your-computer
    ports:
      - 8080:8080

  envoy-tls:
    image: ${account_id}.dkr.ecr.${region}.amazonaws.com/envoy-tls:${envoy_tls_tag}
    init: true
    restart: always
    build:
      context: envoy-tls
    environment:
      ENVOY_TLS_DOMAIN_NAME: test-backend.arkcase.lan
      ENVOY_TLS_UPSTREAM_HOST: test-backend
      ENVOY_TLS_UPSTREAM_PORT: 8080
    ports:
      - 8443:8443
      - 9901:9901
