version: "2.4"  # docker-compose version 3 doesn't support "init: true"

services:
  test-backend:
    depends_on: [ envoy-tls ]
    image: 300674751221.dkr.ecr.us-west-1.amazonaws.com/test-backend:2
    init: true
    restart: always
    build:
      context: test-backend
    environment:
      - HOSTNAME=your-computer
    ports:
      - 8080:8080

  envoy-tls:
    image: 300674751221.dkr.ecr.us-west-1.amazonaws.com/envoy-tls:3
    init: true
    restart: always
    build:
      context: envoy-tls
    environment:
      ENVOY_TLS_DOMAIN_NAME: arkcase.lan
      ENVOY_TLS_UPSTREAM_HOST: test-backend
      ENVOY_TLS_UPSTREAM_PORT: 8080
    ports:
      - 8443:8443
      - 9901:9901
