# `rootPasswordSecret` is the name of the secret that holds the root password
#
# Note: If a password already exists, you must specify the `oldRootPassword` in
# the secret as well to ensure the root password gets changed.
#
# The secret must be formatted like so (in YAML manifest format):
#
#    apiVersion: v1
#    kind: Secret
#    type: Opaque
#    stringData:
#      rootPassword: superpassword
#      oldRootPassword: oldpass  # Set to empty string "" if there is no existing root password
#
rootPasswordSecret: changeme

# `dbconfigSecrets` is the list of the names of the secrets that hold the database name, username and password for each database.
#
# Each secret must be formatted like so (in YAML manifest format):
#
#    apiVersion: v1
#    kind: Secret
#    type: Opaque
#    stringData:
#      dbname: mydb  # Should be formed only of lowercase alphanumeric characters, or in regex terms: [a-z0-9]+
#      username: alice
#      password: cheshirecat
#
dbconfigSecrets:
  - changeme
  - changemetoo

# `storageClass` is the name of the storage class to use for MariaDB's persistent volume
storageClass: standard

# `storageSizeGb` is the size of the storage for MariaDB's persistent volume, in GiB
storageSizeGb: 2

resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

# Set `enableMetrics` to `true` to get the pods to export Prometheus metrics
enableMetrics: true

# `metricsPort` is the port to open to allow Prometheus to scrape metrics
metricsPort: 9104
