# `namespace` is the namespace where MariaDB should be deployed
namespace: arkcase

# `rootPassword` is the password for the MariaDB root user. If a password already exists, specify it as the `oldRootPassword` variable to ensure it gets changed to `rootPassword`.
rootPassword: superpass

# `oldRootPassword` is the existing password for the MariaDB root user
# oldRootPassword: root

# `dbconfig` is the list of databases, usernames and passwords
# NB: `dbname` should be formed only of lowercase alphanumeric characters, or
#     in regex terms: [a-z0-9]+
dbconfig:
  - dbname: db1
    username: user1
    password: pass1
  - dbname: db2
    username: user2
    password: pass2
  - dbname: db3
    username: user3
    password: pass3

# `storageClass` is the name of the storage class to use for MariaDB's persistent volume
storageClass: standard

# `storageSizeGb` is the size of the storage for MariaDB's persistent volume, in GiB
storageSizeGb: 2

resources: {}
  # If you want to specify resources, uncomment the following lines, adjust
  # them as necessary, and remove the curly braces after 'resources:'.
  #
  # limits:
  #   cpu: 2
  #   memory: 1Gi
  # requests:
  #   cpu: 1
  #   memory: 512Mi

# Set `enableMetrics` to `true` to get the pods to export Prometheus metrics
enableMetrics: true

# `metricsPort` is the port to open to allow Prometheus to scrape metrics
metricsPort: 9104
