apiVersion: v1
kind: Service
metadata:
  name: web-service
  annotations:
    comment: Service for the web microservice
spec:
  selector:
    microservice: web
  ports:
    - port: 8101
      targetPort: 8081
